# Generated by Django 5.2.17 on 2026-08-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_cashregistersession_customer_inventorymovement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='plan',
            field=models.CharField(choices=[('Starter', 'Starter — ₱500/month'), ('Pro', 'Pro — ₱1,100/month')], max_length=20),
        ),
    ]
