# Generated by Django 5.2.17 on 2026-08-08 01:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def migrate_shared_registers_and_amounts(apps, schema_editor):
    CashRegisterSession = apps.get_model('pos', 'CashRegisterSession')
    CashRegisterActivity = apps.get_model('pos', 'CashRegisterActivity')
    SubscriptionRequest = apps.get_model('pos', 'SubscriptionRequest')

    for session in CashRegisterSession.objects.all().iterator():
        opened_at = django.utils.timezone.localtime(session.opened_at)
        CashRegisterSession.objects.filter(pk=session.pk).update(business_date=opened_at.date())

    open_store_ids = (
        CashRegisterSession.objects.filter(closed_at__isnull=True)
        .values_list('store_id', flat=True)
        .distinct()
    )
    for store_id in open_store_ids:
        sessions = list(
            CashRegisterSession.objects.filter(store_id=store_id, closed_at__isnull=True)
            .order_by('opened_at', 'pk')
        )
        for duplicate in sessions[1:]:
            CashRegisterSession.objects.filter(pk=duplicate.pk).update(closed_at=duplicate.opened_at)

    for session in CashRegisterSession.objects.all().iterator():
        activity = CashRegisterActivity.objects.create(
            register_id=session.pk,
            user_id=session.user_id,
            start_reason='Opened',
            end_reason='Final close' if session.closed_at else '',
            ended_at=session.closed_at,
            notes='Migrated from the previous per-staff register history.',
        )
        CashRegisterActivity.objects.filter(pk=activity.pk).update(started_at=session.opened_at)

    prices = {'Starter': 500, 'Pro': 1100}
    for plan, amount in prices.items():
        SubscriptionRequest.objects.filter(plan=plan, amount=0).update(amount=amount)


class Migration(migrations.Migration):

    # PostgreSQL must commit the legacy-row updates before creating the new
    # conditional unique indexes, otherwise pending FK trigger events block it.
    atomic = False

    dependencies = [
        ('pos', '0007_alter_subscriptionrequest_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegisterActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_reason', models.CharField(choices=[('Opened', 'Opened daily register'), ('Resumed', 'Resumed shared register'), ('Handover', 'Took over from another staff member')], max_length=20)),
                ('end_reason', models.CharField(blank=True, choices=[('Logout', 'Staff logged out'), ('Handover', 'Handed over'), ('Final close', 'Register closed for the day')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='cashregistersession',
            name='one_open_register_per_store_user',
        ),
        migrations.AddField(
            model_name='cashregistersession',
            name='business_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='contact_details',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='payer_name',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='provider_checkout_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='provider_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='provider_reference',
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_subscription_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='payment_method',
            field=models.CharField(choices=[('Bank transfer', 'Landbank transfer'), ('Cash', 'Cash'), ('Maya', 'Online card / Maya Checkout')], max_length=30),
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending verification'), ('Awaiting payment', 'Awaiting online payment'), ('Approved', 'Approved and activated'), ('Rejected', 'Rejected'), ('Failed', 'Payment failed'), ('Cancelled', 'Payment cancelled')], default='Pending', max_length=24),
        ),
        migrations.AddField(
            model_name='cashregisteractivity',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='pos.cashregistersession'),
        ),
        migrations.AddField(
            model_name='cashregisteractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='register_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(migrate_shared_registers_and_amounts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='cashregistersession',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True)), fields=('store',), name='one_open_register_per_store'),
        ),
        migrations.AddConstraint(
            model_name='cashregisteractivity',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('register',), name='one_active_staff_per_register'),
        ),
    ]
