# Generated by Django 5.2.17 on 2026-08-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_cashregisteractivity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('business_name', models.CharField(max_length=160)),
                ('business_type', models.CharField(blank=True, max_length=80)),
                ('preferred_schedule', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Scheduled', 'Scheduled'), ('Closed', 'Closed')], default='New', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cafe', 'Cafe products'), ('Coffee and Tea', 'Coffee and tea'), ('Drinks', 'Drinks'), ('Pastry', 'Pastry'), ('Meals', 'Meals'), ('Beverages', 'Beverages'), ('Snacks', 'Snacks and confectionery'), ('Canned Goods', 'Canned and packaged goods'), ('Pantry', 'Pantry and cooking essentials'), ('Fresh and Frozen', 'Fresh and frozen goods'), ('Household', 'Household supplies'), ('Clothing', 'Clothing'), ('Footwear', 'Footwear'), ('Fashion Accessories', 'Fashion accessories'), ('Gadgets', 'Gadgets'), ('Mobile Accessories', 'Mobile accessories'), ('Electronics', 'Electronics'), ('Pet Food', 'Pet food'), ('Pet Supplies', 'Pet supplies'), ('Hardware', 'Hardware'), ('Tools', 'Tools'), ('General Merchandise', 'General merchandise'), ('Cosmetics', 'Cosmetics'), ('Personal Care', 'Personal care'), ('Other', 'Other')], default='Other', max_length=40),
        ),
    ]
