# Generated by Django 5.2.17 on 2026-08-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_demorequest_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='plan',
            field=models.CharField(choices=[('Starter', 'Starter — ₱399/month'), ('Pro', 'Pro — ₱799/month')], max_length=20),
        ),
    ]
