# Generated by Django 5.2.17 on 2026-08-08 02:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_alter_subscriptionrequest_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='external_order_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='sale',
            name='offline_notes',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='sale',
            name='source',
            field=models.CharField(choices=[('Online', 'Online checkout'), ('Offline CSV', 'Offline recovery CSV')], default='Online', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Offline sale', 'Offline recovery sale'), ('Adjustment', 'Adjustment'), ('Stocktake', 'Stocktake'), ('Transfer out', 'Transfer out'), ('Transfer in', 'Transfer in'), ('Purchase', 'Purchase received'), ('Return', 'Sale reversal'), ('Import', 'CSV import')], max_length=24),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('external_order_id', ''), _negated=True), fields=('store', 'external_order_id'), name='unique_store_offline_order_id'),
        ),
    ]
