# Generated by Django 5.2.17 on 2026-08-08 03:20

import django.db.models.deletion
from django.db import migrations, models


PRESETS = {
    'Cafe': ('Coffee and Tea', 'Drinks', 'Pastry', 'Meals', 'Snacks', 'Other'),
    'Grocery': ('Beverages', 'Snacks', 'Canned Goods', 'Pantry', 'Fresh and Frozen', 'Household', 'Other'),
    'Fashion': ('Clothing', 'Footwear', 'Fashion Accessories', 'Other'),
    'Electronics': ('Gadgets', 'Mobile Accessories', 'Electronics', 'Other'),
    'Pet Supplies': ('Pet Food', 'Pet Supplies', 'Other'),
    'Hardware': ('Hardware', 'Tools', 'General Merchandise', 'Other'),
    'Beauty': ('Cosmetics', 'Personal Care', 'Other'),
    'General Retail': ('General Merchandise', 'Other'),
}


def prepare_store_categories(apps, schema_editor):
    StoreSettings = apps.get_model('pos', 'StoreSettings')
    Product = apps.get_model('pos', 'Product')
    ProductCategory = apps.get_model('pos', 'ProductCategory')

    for store in StoreSettings.objects.all().iterator():
        used_names = list(
            Product.objects.filter(store_id=store.pk)
            .exclude(category='')
            .values_list('category', flat=True)
            .distinct()
        )
        used_set = set(used_names)
        scores = {
            store_type: len((set(names) - {'Other'}) & used_set)
            for store_type, names in PRESETS.items()
            if store_type != 'General Retail'
        }
        best_type = max(scores, key=scores.get) if scores and max(scores.values()) else 'General Retail'
        store.store_type = best_type
        store.save(update_fields=['store_type'])

        preset_names = PRESETS[best_type]
        for name in (*preset_names, *used_names):
            ProductCategory.objects.get_or_create(
                store_id=store.pk,
                name=name,
                defaults={'is_custom': name not in preset_names},
            )


def reverse_store_categories(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_sale_external_order_id_sale_offline_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='store_type',
            field=models.CharField(choices=[('Cafe', 'Cafe'), ('Grocery', 'Minimart / specialty grocery'), ('Fashion', 'Clothing / footwear boutique'), ('Electronics', 'Gadget / accessory shop'), ('Pet Supplies', 'Pet-supply store'), ('Hardware', 'Hardware / general merchandise'), ('Beauty', 'Cosmetics / personal care retailer'), ('General Retail', 'General retail / other')], default='General Retail', help_text='Controls the product categories initially available to this store.', max_length=24),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='Other', max_length=60),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('is_custom', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='pos.storesettings')),
            ],
            options={
                'verbose_name': 'product category',
                'verbose_name_plural': 'product categories',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('store', 'name'), name='unique_store_product_category')],
            },
        ),
        migrations.RunPython(prepare_store_categories, reverse_store_categories),
    ]
